when:
  - event: push
    branch: [main, work/jbb/woodpecker]
  - event: cron
    cron: daily-import

steps:
  fetch:
    image: ghcr.io/public-transport/transitous/import:latest
    commands:
      - git submodule update --init --checkout --remote
      - ./ci/fetch-feeds.py timer
  import:
    image: ghcr.io/public-transport/transitous/import:latest
    commands:
      - ./src/generate-attribution.py
      - ./src/generate-motis-config.py import
      - cd out && ../ci/motis-import.py > /dev/null && cd ..
      - src/generate-motis-config.py full
  push:
    image: ghcr.io/public-transport/transitous/import:latest
    secrets: [ RSYNC_PRIVATE_KEY ]
    commands:
      - echo "$${RSYNC_PRIVATE_KEY}" > deploy_key
      - chmod 600 ./deploy_key
      - "rsync -avz --progress --delete -e 'ssh -i ./deploy_key -p 22 -o StrictHostKeyChecking=no' out/ rsync@vm-motis.spline.de:"
      - rm deploy_key
